[package]
name = "display_sensor_data"
version = "0.1.0"
authors = ["sambenko <sam.benko@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp32s3-hal = { version = "0.8.0", optional = true, features = [ "rt" ] }
esp-wifi = { git = "https://github.com/esp-rs/esp-wifi", package = "esp-wifi", features = ["esp32s3","esp32s3-async", "esp-now", "phy-enable-usb"] }
esp-backtrace = { git = "https://github.com/esp-rs/esp-backtrace", version = "0.6.0", features = ["esp32s3", "panic-handler", "print-uart"] }
esp-println = { version = "0.4.0", features = ["esp32s3"] }
embedded-hal = "0.2.3"
embedded-svc = { version = "0.24.0", default-features = false, features = [], optional = true }
embedded-io = "0.4.0"
esp-wifi-sys = { git = "https://github.com/esp-rs/esp-wifi", package = "esp-wifi-sys" }
heapless = { version = "0.7.14", default-features = false }
display-interface-spi = "0.4"
mipidsi = "0.6.0"
embedded-graphics = "0.7"
profont = "0.6.1"
embedded-graphics-framebuf = "0.2.0"
ui = { path = "./ui"}

[features]
default = [ "esp32s3-hal/eh1" ]
